version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: bharosa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bharosa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: bharosa-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: bharosa-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata: {}